### ISSUE TITLE
Does the password changes in auth_user if it is changed by a Front-end client in Firebase?

### ISSUE THREAD

**Issue by Arka-cell** [garyburgmann/drf-firebase-auth#27]
Suppose that a password is changed on Firebase, will it be changed on auth_user? I am using drf_firebase_auth in a project and wanted to know this details.

**Comment by garyburgmann** [comment]
`drf_firebase_auth` has no interest in the user password. Typically someone uses a service like Firebase for the benefit of pushing auth off to another modular service.

as per the django documentation:

https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_user

Users, if created, use `password=None`
