### ISSUE TITLE
Use with IsAuthenticatedOrReadOnly

### ISSUE THREAD

**Issue by quorth0n** [garyburgmann/drf-firebase-auth#5]
No Authorization header returns `Invalid Authorization header format, expecting: JWT <token>.`, and a blank one results in `JWT was found to be invalid, or the App’s project ID cannot be determined.` Is this the intended behavior? I have `ALLOW_ANONYMOUS_REQUESTS` set to `True`.

**Comment by whirish** [comment]
Never mind, I was building from pip, and it seems the latest commits (#3) haven't been built yet.

**Comment by waleko** [comment]
@garyburgmann How about publishing the current version to pypi, so it's accessible via pip?

**Comment by garyburgmann** [comment]
Hey @waleko, I know I have been slack with this, I have personally moved away from this in favor of authenticating with a view and piggy backing off of the djangorestframework-jwt lib.
I will review this over the weekend, and push up the changes to pypi
